package typefile

// Person Pythonありがとう
type Person struct {
	IsDispStatus           *string   `json:"is_disp_status"`
	VShuzokuID             *string   `json:"V_shuzoku_id"`
	ShuzokuName            *string   `json:"shuzoku_name"`
	SpecialShuzokuID       *string   `json:"special_shuzoku_id"`
	SpecialShuzokuName     *string   `json:"special_shuzoku_name"`
	ShuzokuTokucho         *string   `json:"shuzoku_tokucho"`
	UmareID                *string   `json:"umare_id"`
	UmareName              *string   `json:"umare_name"`
	NWaza                  *string   `json:"N_waza"`
	NKarada                *string   `json:"N_karada"`
	NKokoro                *string   `json:"N_kokoro"`
	TokuchoKyoukaAdd       *string   `json:"tokucho_kyouka_add"`
	VNc1                   *string   `json:"V_NC1"`
	VNc2                   *string   `json:"V_NC2"`
	VNc3                   *string   `json:"V_NC3"`
	VNc4                   *string   `json:"V_NC4"`
	VNc5                   *string   `json:"V_NC5"`
	VNc6                   *string   `json:"V_NC6"`
	LifeResistBase         *string   `json:"life_resist_base"`
	MentalResistBase       *string   `json:"mental_resist_base"`
	HpBase                 *string   `json:"HP_base"`
	MpBase                 *string   `json:"MP_base"`
	MamonoSikibetuBase     *string   `json:"mamono_sikibetu_base"`
	MamonoChishikiBase     *string   `json:"mamono_chishiki_base"`
	SenseiBase             *string   `json:"sensei_base"`
	IDoBase                *string   `json:"ido_base"`
	ZenryokuIDoBase        *string   `json:"zenryoku_ido_base"`
	SessionNum             *string   `json:"session_num"`
	Ns1                    *string   `json:"NS1"`
	Ns2                    *string   `json:"NS2"`
	Ns3                    *string   `json:"NS3"`
	Ns4                    *string   `json:"NS4"`
	Ns5                    *string   `json:"NS5"`
	Ns6                    *string   `json:"NS6"`
	HpTokugi               *string   `json:"HP_tokugi"`
	MpTokugi               *string   `json:"MP_tokugi"`
	IDoTokugi              *string   `json:"ido_tokugi"`
	Nm1                    *string   `json:"NM1"`
	Nm2                    *string   `json:"NM2"`
	Nm3                    *string   `json:"NM3"`
	Nm4                    *string   `json:"NM4"`
	Nm5                    *string   `json:"NM5"`
	Nm6                    *string   `json:"NM6"`
	LifeResistMod          *string   `json:"life_resist_mod"`
	MentalResistMod        *string   `json:"mental_resist_mod"`
	HpMod                  *string   `json:"HP_mod"`
	MpMod                  *string   `json:"MP_mod"`
	MamonoChishikiMod      *string   `json:"mamono_chishiki_mod"`
	SenseiMod              *string   `json:"sensei_mod"`
	IDoMod                 *string   `json:"ido_mod"`
	ZenryokuIDoMod         *string   `json:"zenryoku_ido_mod"`
	Np1                    *string   `json:"NP1"`
	Np2                    *string   `json:"NP2"`
	Np3                    *string   `json:"NP3"`
	Np4                    *string   `json:"NP4"`
	Np5                    *string   `json:"NP5"`
	Np6                    *string   `json:"NP6"`
	LifeResist             *string   `json:"life_resist"`
	MentalResist           *string   `json:"mental_resist"`
	Hp                     *string   `json:"HP"`
	Mp                     *string   `json:"MP"`
	MamonoSikibetu         *string   `json:"mamono_sikibetu"`
	MamonoChishiki         *string   `json:"mamono_chishiki"`
	Sensei                 *string   `json:"sensei"`
	IDo                    *string   `json:"ido"`
	ZenryokuIDo            *string   `json:"zenryoku_ido"`
	Nb1                    *string   `json:"NB1"`
	Nb2                    *string   `json:"NB2"`
	Nb3                    *string   `json:"NB3"`
	Nb4                    *string   `json:"NB4"`
	Nb5                    *string   `json:"NB5"`
	Nb6                    *string   `json:"NB6"`
	IsDispGinou            *string   `json:"is_disp_ginou"`
	Lv                     *string   `json:"lv"`
	MagicLvSum             *string   `json:"magic_lv_sum"`
	NotSelGinou            *string   `json:"not_sel_ginou"`
	VGlv1                  *string   `json:"V_GLv1"`
	VGlv5                  *string   `json:"V_GLv5"`
	VGlv10                 *string   `json:"V_GLv10"`
	CreateExp              *string   `json:"create_exp"`
	UsedExp                *string   `json:"used_exp"`
	NowExp                 *string   `json:"now_exp"`
	VGlv2                  *string   `json:"V_GLv2"`
	VGlv6                  *string   `json:"V_GLv6"`
	VGlv11                 *string   `json:"V_GLv11"`
	CreateGinouExp         *string   `json:"create_ginou_exp"`
	VGlv3                  *string   `json:"V_GLv3"`
	VGlv7                  *string   `json:"V_GLv7"`
	VGlv12                 *string   `json:"V_GLv12"`
	CreateGinouName        *string   `json:"create_ginou_name"`
	VGlv4                  *string   `json:"V_GLv4"`
	PriestSinkou           *string   `json:"priest_sinkou"`
	VGlv13                 *string   `json:"V_GLv13"`
	SessionExp             *string   `json:"session_exp"`
	VGlv8                  *string   `json:"V_GLv8"`
	VGlv14                 *string   `json:"V_GLv14"`
	PcRank                 *string   `json:"pc_rank"`
	VGlv20                 *string   `json:"V_GLv20"`
	VGlv9                  *string   `json:"V_GLv9"`
	VGlv16                 *string   `json:"V_GLv16"`
	VGlv22                 *string   `json:"V_GLv22"`
	VGlv17                 *string   `json:"V_GLv17"`
	VGlv15                 *string   `json:"V_GLv15"`
	VGlv23                 *string   `json:"V_GLv23"`
	VGlv21                 *string   `json:"V_GLv21"`
	VGlv18                 *string   `json:"V_GLv18"`
	VGlv19                 *string   `json:"V_GLv19"`
	VSpecialLv             *string   `json:"V_special_lv"`
	SpecialGetHpmp         *string   `json:"special_get_hpmp"`
	SpecialGetRegist       *string   `json:"special_get_regist"`
	SpecialGetNm           *string   `json:"special_get_nm"`
	SpecialGetBbj          *string   `json:"special_get_bbj"`
	SpecialGetOthers       *string   `json:"special_get_others"`
	IsDispSentotokugi      *string   `json:"is_disp_sentotokugi"`
	TokugiMode             *string   `json:"tokugi_mode"`
	StNameFig1             *string   `json:"ST_name_fig1"`
	StIDFig1               *string   `json:"ST_id_fig1"`
	StKoukaFig1            *string   `json:"ST_kouka_fig1"`
	StZenteiFig1           *string   `json:"ST_zentei_fig1"`
	StPageFig1             *string   `json:"ST_page_fig1"`
	StNameGrp1             *string   `json:"ST_name_grp1"`
	StIDGrp1               *string   `json:"ST_id_grp1"`
	StKoukaGrp1            *string   `json:"ST_kouka_grp1"`
	StZenteiGrp1           *string   `json:"ST_zentei_grp1"`
	StPageGrp1             *string   `json:"ST_page_grp1"`
	StNameGrp2             *string   `json:"ST_name_grp2"`
	StIDGrp2               *string   `json:"ST_id_grp2"`
	StKoukaGrp2            *string   `json:"ST_kouka_grp2"`
	StZenteiGrp2           *string   `json:"ST_zentei_grp2"`
	StPageGrp2             *string   `json:"ST_page_grp2"`
	StNameGrp4             *string   `json:"ST_name_grp4"`
	StKoukaGrp4            *string   `json:"ST_kouka_grp4"`
	StZenteiGrp4           *string   `json:"ST_zentei_grp4"`
	StPageGrp4             *string   `json:"ST_page_grp4"`
	StNameGrp3             *string   `json:"ST_name_grp3"`
	StIDGrp3               *string   `json:"ST_id_grp3"`
	StKoukaGrp3            *string   `json:"ST_kouka_grp3"`
	StZenteiGrp3           *string   `json:"ST_zentei_grp3"`
	StPageGrp3             *string   `json:"ST_page_grp3"`
	StNameFiggrp           *string   `json:"ST_name_figgrp"`
	StIDFiggrp             *string   `json:"ST_id_figgrp"`
	StKoukaFiggrp          *string   `json:"ST_kouka_figgrp"`
	StZenteiFiggrp         *string   `json:"ST_zentei_figgrp"`
	StPageFiggrp           *string   `json:"ST_page_figgrp"`
	StNameMagicmaster      *string   `json:"ST_name_magicmaster"`
	StKoukaMagicmaster     *string   `json:"ST_kouka_magicmaster"`
	StZenteiMagicmaster    *string   `json:"ST_zentei_magicmaster"`
	StPageMagicmaster      *string   `json:"ST_page_magicmaster"`
	StNameScout1           *string   `json:"ST_name_scout1"`
	StIDScout1             *string   `json:"ST_id_scout1"`
	StKoukaScout1          *string   `json:"ST_kouka_scout1"`
	StZenteiScout1         *string   `json:"ST_zentei_scout1"`
	StPageScout1           *string   `json:"ST_page_scout1"`
	StNameScout2           *string   `json:"ST_name_scout2"`
	StIDScout2             *string   `json:"ST_id_scout2"`
	StKoukaScout2          *string   `json:"ST_kouka_scout2"`
	StZenteiScout2         *string   `json:"ST_zentei_scout2"`
	StPageScout2           *string   `json:"ST_page_scout2"`
	StNameScout3           *string   `json:"ST_name_scout3"`
	StIDScout3             *string   `json:"ST_id_scout3"`
	StKoukaScout3          *string   `json:"ST_kouka_scout3"`
	StZenteiScout3         *string   `json:"ST_zentei_scout3"`
	StPageScout3           *string   `json:"ST_page_scout3"`
	StNameScout4           *string   `json:"ST_name_scout4"`
	StIDScout4             *string   `json:"ST_id_scout4"`
	StKoukaScout4          *string   `json:"ST_kouka_scout4"`
	StZenteiScout4         *string   `json:"ST_zentei_scout4"`
	StPageScout4           *string   `json:"ST_page_scout4"`
	StNameScout5           *string   `json:"ST_name_scout5"`
	StIDScout5             *string   `json:"ST_id_scout5"`
	StKoukaScout5          *string   `json:"ST_kouka_scout5"`
	StZenteiScout5         *string   `json:"ST_zentei_scout5"`
	StPageScout5           *string   `json:"ST_page_scout5"`
	StNameRanger1          *string   `json:"ST_name_ranger1"`
	StIDRanger1            *string   `json:"ST_id_ranger1"`
	StKoukaRanger1         *string   `json:"ST_kouka_ranger1"`
	StZenteiRanger1        *string   `json:"ST_zentei_ranger1"`
	StPageRanger1          *string   `json:"ST_page_ranger1"`
	StNameRanger2          *string   `json:"ST_name_ranger2"`
	StIDRanger2            *string   `json:"ST_id_ranger2"`
	StKoukaRanger2         *string   `json:"ST_kouka_ranger2"`
	StZenteiRanger2        *string   `json:"ST_zentei_ranger2"`
	StPageRanger2          *string   `json:"ST_page_ranger2"`
	StNameRanger3          *string   `json:"ST_name_ranger3"`
	StIDRanger3            *string   `json:"ST_id_ranger3"`
	StKoukaRanger3         *string   `json:"ST_kouka_ranger3"`
	StZenteiRanger3        *string   `json:"ST_zentei_ranger3"`
	StPageRanger3          *string   `json:"ST_page_ranger3"`
	StNameRanger4          *string   `json:"ST_name_ranger4"`
	StIDRanger4            *string   `json:"ST_id_ranger4"`
	StKoukaRanger4         *string   `json:"ST_kouka_ranger4"`
	StZenteiRanger4        *string   `json:"ST_zentei_ranger4"`
	StPageRanger4          *string   `json:"ST_page_ranger4"`
	StNameRanger5          *string   `json:"ST_name_ranger5"`
	StIDRanger5            *string   `json:"ST_id_ranger5"`
	StKoukaRanger5         *string   `json:"ST_kouka_ranger5"`
	StZenteiRanger5        *string   `json:"ST_zentei_ranger5"`
	StPageRanger5          *string   `json:"ST_page_ranger5"`
	StNameSage1            *string   `json:"ST_name_sage1"`
	StIDSage1              *string   `json:"ST_id_sage1"`
	StKoukaSage1           *string   `json:"ST_kouka_sage1"`
	StZenteiSage1          *string   `json:"ST_zentei_sage1"`
	StPageSage1            *string   `json:"ST_page_sage1"`
	StNameSage2            *string   `json:"ST_name_sage2"`
	StIDSage2              *string   `json:"ST_id_sage2"`
	StKoukaSage2           *string   `json:"ST_kouka_sage2"`
	StZenteiSage2          *string   `json:"ST_zentei_sage2"`
	StPageSage2            *string   `json:"ST_page_sage2"`
	StNameSage3            *string   `json:"ST_name_sage3"`
	StIDSage3              *string   `json:"ST_id_sage3"`
	StKoukaSage3           *string   `json:"ST_kouka_sage3"`
	StZenteiSage3          *string   `json:"ST_zentei_sage3"`
	StPageSage3            *string   `json:"ST_page_sage3"`
	StNameSage4            *string   `json:"ST_name_sage4"`
	StIDSage4              *string   `json:"ST_id_sage4"`
	StKoukaSage4           *string   `json:"ST_kouka_sage4"`
	StZenteiSage4          *string   `json:"ST_zentei_sage4"`
	StPageSage4            *string   `json:"ST_page_sage4"`
	StNameSage5            *string   `json:"ST_name_sage5"`
	StIDSage5              *string   `json:"ST_id_sage5"`
	StKoukaSage5           *string   `json:"ST_kouka_sage5"`
	StZenteiSage5          *string   `json:"ST_zentei_sage5"`
	StPageSage5            *string   `json:"ST_page_sage5"`
	StLv                   *[]string `json:"ST_lv"`
	VStID                  *[]string `json:"V_ST_id"`
	StName                 *[]string `json:"ST_name"`
	StTlv                  *[]string `json:"ST_tlv"`
	StKouka                *[]string `json:"ST_kouka"`
	StZentei               *[]string `json:"ST_zentei"`
	StPage                 *[]string `json:"ST_page"`
	HikinzokuShujuku       *string   `json:"hikinzoku_shujuku"`
	KinzokuShujuku         *string   `json:"kinzoku_shujuku"`
	TateShujuku            *string   `json:"tate_shujuku"`
	IsDispEquip            *string   `json:"is_disp_equip"`
	Glv1Dsp                *string   `json:"GLv1_dsp"`
	G1Hit                  *string   `json:"G1_hit"`
	G1Damage               *string   `json:"G1_damage"`
	G1Kaihi                *string   `json:"G1_kaihi"`
	Glv2Dsp                *string   `json:"GLv2_dsp"`
	G2Hit                  *string   `json:"G2_hit"`
	G2Damage               *string   `json:"G2_damage"`
	G2Kaihi                *string   `json:"G2_kaihi"`
	Glv3Dsp                *string   `json:"GLv3_dsp"`
	G3Hit                  *string   `json:"G3_hit"`
	G3Damage               *string   `json:"G3_damage"`
	G3Kaihi                *string   `json:"G3_kaihi"`
	Glv4Dsp                *string   `json:"GLv4_dsp"`
	G4Hit                  *string   `json:"G4_hit"`
	G4Damage               *string   `json:"G4_damage"`
	G4Kaihi                *string   `json:"G4_kaihi"`
	Glv13Dsp               *string   `json:"GLv13_dsp"`
	G13Hit                 *string   `json:"G13_hit"`
	G13Damage              *string   `json:"G13_damage"`
	Glv17Dsp               *string   `json:"GLv17_dsp"`
	G17Hit                 *string   `json:"G17_hit"`
	G17Damage              *string   `json:"G17_damage"`
	G17Kaihi               *string   `json:"G17_kaihi"`
	Np3Dsp                 *string   `json:"NP3_dsp"`
	Np3Upper               *string   `json:"NP3_upper"`
	ArmInput               *string   `json:"arm_input"`
	ArmsIsInput            *[]string `json:"arms_is_input"`
	VArmsID                *[]string `json:"V_arms_id"`
	ArmsName               *[]string `json:"arms_name"`
	ArmsIsEquip            *[]string `json:"arms_is_equip"`
	ArmsPrice              *[]string `json:"arms_price"`
	ArmsYoho               *[]string `json:"arms_yoho"`
	ArmsHitsukin           *[]string `json:"arms_hitsukin"`
	ArmsIsSenyou           *[]string `json:"arms_is_senyou"`
	ArmsHitMod             *[]string `json:"arms_hit_mod"`
	VArmsHitGinou          *[]string `json:"V_arms_hit_ginou"`
	ArmsHit                *[]string `json:"arms_hit"`
	ArmsIryoku             *[]string `json:"arms_iryoku"`
	ArmsCritical           *[]string `json:"arms_critical"`
	ArmsDamageMod          *[]string `json:"arms_damage_mod"`
	ArmsDamage             *[]string `json:"arms_damage"`
	ArmsPage               *[]string `json:"arms_page"`
	ArmsCate               *[]string `json:"arms_cate"`
	ArmsRank               *[]string `json:"arms_rank"`
	ArmsMemo               *[]string `json:"arms_memo"`
	ArmEquip               *string   `json:"arm_equip"`
	ArmsPriceSum           *string   `json:"arms_price_sum"`
	ArmorName              *string   `json:"armor_name"`
	ArmorHitsukin          *string   `json:"armor_hitsukin"`
	ArmorKaihi             *string   `json:"armor_kaihi"`
	ArmorBougo             *string   `json:"armor_bougo"`
	ArmorPrice             *string   `json:"armor_price"`
	ArmorMemo              *string   `json:"armor_memo"`
	ShieldName             *string   `json:"shield_name"`
	ShieldHitsukin         *string   `json:"shield_hitsukin"`
	ShieldKaihi            *string   `json:"shield_kaihi"`
	ShieldBougo            *string   `json:"shield_bougo"`
	ShieldPrice            *string   `json:"shield_price"`
	ShieldMemo             *string   `json:"shield_memo"`
	Shield2Name            *string   `json:"shield2_name"`
	Shield2Hitsukin        *string   `json:"shield2_hitsukin"`
	Shield2Kaihi           *string   `json:"shield2_kaihi"`
	Shield2Bougo           *string   `json:"shield2_bougo"`
	Shield2Price           *string   `json:"shield2_price"`
	Shield2Memo            *string   `json:"shield2_memo"`
	VArmerType             *string   `json:"V_armer_type"`
	BouguKaihiTokugi       *string   `json:"bougu_kaihi_tokugi"`
	BouguBougoTokugi       *string   `json:"bougu_bougo_tokugi"`
	BouguKaihiMod          *string   `json:"bougu_kaihi_mod"`
	BouguBougoMod          *string   `json:"bougu_bougo_mod"`
	VKaihiGinou            *string   `json:"V_kaihi_ginou"`
	KaihiGinouName         *string   `json:"kaihi_ginou_name"`
	Kaihi                  *string   `json:"kaihi"`
	Bougo                  *string   `json:"bougo"`
	BouguPriceSum          *string   `json:"bougu_price_sum"`
	ArmsHitTokugi          *string   `json:"arms_hit_tokugi"`
	EeqHitExtend           *string   `json:"eeq_hit_extend"`
	EeqDmgExtend           *string   `json:"eeq_dmg_extend"`
	EeqSplExtend           *string   `json:"eeq_spl_extend"`
	EeqEvdExtend           *string   `json:"eeq_evd_extend"`
	IsDispPhysical         *string   `json:"is_disp_physical"`
	PhyBuiName             *[]string `json:"phy_bui_name"`
	PhyBuiAttack           *[]string `json:"phy_bui_attack"`
	PhyBuiYoho             *[]string `json:"phy_bui_yoho"`
	PhyBuiHitMod           *[]string `json:"phy_bui_hit_mod"`
	PhyBuiHit              *[]string `json:"phy_bui_hit"`
	PhyBuiIryoku           *[]string `json:"phy_bui_iryoku"`
	PhyBuiCritical         *[]string `json:"phy_bui_critical"`
	PhyBuiDamageMod        *[]string `json:"phy_bui_damage_mod"`
	PhyBuiDamage           *[]string `json:"phy_bui_damage"`
	PhyBuiPage             *[]string `json:"phy_bui_page"`
	PhyBuiRank             *[]string `json:"phy_bui_rank"`
	PhyBuiKaihiMod         *[]string `json:"phy_bui_kaihi_mod"`
	PhyBuiKaihi            *[]string `json:"phy_bui_kaihi"`
	PhyBuiBougo            *[]string `json:"phy_bui_bougo"`
	PhyBuiHp               *[]string `json:"phy_bui_hp"`
	PhyBuiMp               *[]string `json:"phy_bui_mp"`
	PhyBuiMemo             *[]string `json:"phy_bui_memo"`
	MsLv                   *[]string `json:"MS_lv"`
	MsName                 *[]string `json:"MS_name"`
	MsType                 *[]string `json:"MS_type"`
	MsKouka                *[]string `json:"MS_kouka"`
	MsPage                 *[]string `json:"MS_page"`
	PhyBuiCoreKaihiTokugi  *string   `json:"phy_bui_core_kaihi_tokugi"`
	PhyBuiCoreDamageTokugi *string   `json:"phy_bui_core_damage_tokugi"`
	PhyBuiKaihiTokugi      *string   `json:"phy_bui_kaihi_tokugi"`
	PhyBuiDamageTokugi     *string   `json:"phy_bui_damage_tokugi"`
	IsDispAccessory        *string   `json:"is_disp_accessory"`
	Acce1Senyou            *[]string `json:"acce1_senyou"`
	Acce1Name              *[]string `json:"acce1_name"`
	Acce1Price             *[]string `json:"acce1_price"`
	Acce1Memo              *[]string `json:"acce1_memo"`
	Acce1Valid             *[]string `json:"acce1_valid"`
	Acce1St                *[]string `json:"acce1_st"`
	Acce1Stv               *[]string `json:"acce1_stv"`
	Acce2Senyou            *[]string `json:"acce2_senyou"`
	Acce2Name              *[]string `json:"acce2_name"`
	Acce2Price             *[]string `json:"acce2_price"`
	Acce2Memo              *[]string `json:"acce2_memo"`
	Acce2Valid             *[]string `json:"acce2_valid"`
	Acce2St                *[]string `json:"acce2_st"`
	Acce2Stv               *[]string `json:"acce2_stv"`
	Acce3Senyou            *[]string `json:"acce3_senyou"`
	Acce3Name              *[]string `json:"acce3_name"`
	Acce3Price             *[]string `json:"acce3_price"`
	Acce3Memo              *[]string `json:"acce3_memo"`
	Acce3Valid             *[]string `json:"acce3_valid"`
	Acce3St                *[]string `json:"acce3_st"`
	Acce3Stv               *[]string `json:"acce3_stv"`
	Acce4Senyou            *[]string `json:"acce4_senyou"`
	Acce4Name              *[]string `json:"acce4_name"`
	Acce4Price             *[]string `json:"acce4_price"`
	Acce4Memo              *[]string `json:"acce4_memo"`
	Acce4Valid             *[]string `json:"acce4_valid"`
	Acce4St                *[]string `json:"acce4_st"`
	Acce4Stv               *[]string `json:"acce4_stv"`
	Acce5Senyou            *[]string `json:"acce5_senyou"`
	Acce5Name              *[]string `json:"acce5_name"`
	Acce5Price             *[]string `json:"acce5_price"`
	Acce5Memo              *[]string `json:"acce5_memo"`
	Acce5Valid             *[]string `json:"acce5_valid"`
	Acce5St                *[]string `json:"acce5_st"`
	Acce5Stv               *[]string `json:"acce5_stv"`
	Acce6Senyou            *[]string `json:"acce6_senyou"`
	Acce6Name              *[]string `json:"acce6_name"`
	Acce6Price             *[]string `json:"acce6_price"`
	Acce6Memo              *[]string `json:"acce6_memo"`
	Acce6Valid             *[]string `json:"acce6_valid"`
	Acce6St                *[]string `json:"acce6_st"`
	Acce6Stv               *[]string `json:"acce6_stv"`
	Acce7Senyou            *[]string `json:"acce7_senyou"`
	Acce7Name              *[]string `json:"acce7_name"`
	Acce7Price             *[]string `json:"acce7_price"`
	Acce7Memo              *[]string `json:"acce7_memo"`
	Acce7Valid             *[]string `json:"acce7_valid"`
	Acce7St                *[]string `json:"acce7_st"`
	Acce7Stv               *[]string `json:"acce7_stv"`
	Acce8Senyou            *[]string `json:"acce8_senyou"`
	Acce8Name              *[]string `json:"acce8_name"`
	Acce8Price             *[]string `json:"acce8_price"`
	Acce8Memo              *[]string `json:"acce8_memo"`
	Acce8Valid             *[]string `json:"acce8_valid"`
	Acce8St                *[]string `json:"acce8_st"`
	Acce8Stv               *[]string `json:"acce8_stv"`
	Acce9Senyou            *[]string `json:"acce9_senyou"`
	Acce9Name              *[]string `json:"acce9_name"`
	Acce9Price             *[]string `json:"acce9_price"`
	Acce9Memo              *[]string `json:"acce9_memo"`
	Acce9Valid             *[]string `json:"acce9_valid"`
	Acce9St                *[]string `json:"acce9_st"`
	Acce9Stv               *[]string `json:"acce9_stv"`
	Acce10Senyou           *[]string `json:"acce10_senyou"`
	Acce10Name             *[]string `json:"acce10_name"`
	Acce10Price            *[]string `json:"acce10_price"`
	Acce10Memo             *[]string `json:"acce10_memo"`
	Acce10Valid            *[]string `json:"acce10_valid"`
	Acce10St               *[]string `json:"acce10_st"`
	Acce10Stv              *[]string `json:"acce10_stv"`
	AccePriceSum           *string   `json:"acce_price_sum"`
	IsDispItem             *string   `json:"is_disp_item"`
	ItemName               *[]string `json:"item_name"`
	ItemTanka              *[]string `json:"item_tanka"`
	ItemNum                *[]string `json:"item_num"`
	ItemPrice              *[]string `json:"item_price"`
	ItemMemo               *[]string `json:"item_memo"`
	PriceItemSum           *string   `json:"price_item_sum"`
	PriceEquipSum          *string   `json:"price_equip_sum"`
	Usemindcalc            *string   `json:"useMindCalc"`
	Money                  *string   `json:"money"`
	Debt                   *string   `json:"debt"`
	PriceAllSum            *string   `json:"price_all_sum"`
	IsDispLanguage         *string   `json:"is_disp_language"`
	CreateLanguage         *string   `json:"create_language"`
	GinouLanguage          *string   `json:"ginou_language"`
	Lang3s                 *string   `json:"lang3S"`
	Lang3r                 *string   `json:"lang3R"`
	Lang12s                *string   `json:"lang12S"`
	Lang12r                *string   `json:"lang12R"`
	NowLangNum             *string   `json:"now_lang_num"`
	SynonimLangNum         *string   `json:"synonim_lang_num"`
	CanLangNum             *string   `json:"can_lang_num"`
	VLangTypeID            *[]string `json:"V_lang_type_id"`
	LangTypeName           *[]string `json:"lang_type_name"`
	LangNote               *[]string `json:"lang_note"`
	VLangs                 *[]string `json:"V_langS"`
	VLangr                 *[]string `json:"V_langR"`
	VLangTypeaID           *[]string `json:"V_lang_typeA_id"`
	LangTypeaName          *[]string `json:"lang_typeA_name"`
	VLangsa                *[]string `json:"V_langSA"`
	VLangra                *[]string `json:"V_langRA"`
	IsDispEnhance          *string   `json:"is_disp_enhance"`
	EsLv                   *[]string `json:"ES_lv"`
	EsName                 *[]string `json:"ES_name"`
	EsKoukatime            *[]string `json:"ES_koukatime"`
	EsKouka                *[]string `json:"ES_kouka"`
	EsPage                 *[]string `json:"ES_page"`
	IsDispSong             *string   `json:"is_disp_song"`
	JkLv                   *[]string `json:"JK_lv"`
	JkName                 *[]string `json:"JK_name"`
	JkZentei               *[]string `json:"JK_zentei"`
	JkKouka                *[]string `json:"JK_kouka"`
	JkEishou               *[]string `json:"JK_eishou"`
	JkPage                 *[]string `json:"JK_page"`
	EjukaHitExtend         *string   `json:"ejuka_hit_extend"`
	IsDispRiding           *string   `json:"is_disp_riding"`
	KgLv                   *[]string `json:"KG_lv"`
	KgName                 *[]string `json:"KG_name"`
	KgTiming               *[]string `json:"KG_timing"`
	KgKouka                *[]string `json:"KG_kouka"`
	KgZentei               *[]string `json:"KG_zentei"`
	KgAnimal               *[]string `json:"KG_animal"`
	KgGenju                *[]string `json:"KG_Genju"`
	KgKikai                *[]string `json:"KG_Kikai"`
	KgPage                 *[]string `json:"KG_page"`
	IsDispHujutu           *string   `json:"is_disp_hujutu"`
	HjLv                   *[]string `json:"HJ_lv"`
	HjName                 *[]string `json:"HJ_name"`
	HjZentei               *[]string `json:"HJ_zentei"`
	HjTiming               *[]string `json:"HJ_timing"`
	HjKouka                *[]string `json:"HJ_kouka"`
	HjB                    *[]string `json:"HJ_B"`
	HjA                    *[]string `json:"HJ_A"`
	HjS                    *[]string `json:"HJ_S"`
	HjSs                   *[]string `json:"HJ_SS"`
	HjPage                 *[]string `json:"HJ_page"`
	IsDispHoukou           *string   `json:"is_disp_houkou"`
	HoLv                   *[]string `json:"HO_lv"`
	HoName                 *[]string `json:"HO_name"`
	HoType                 *[]string `json:"HO_type"`
	HoRank                 *[]string `json:"HO_rank"`
	HoKouka                *[]string `json:"HO_kouka"`
	HoPage                 *[]string `json:"HO_page"`
	IsDispUranai           *string   `json:"is_disp_uranai"`
	UrLv                   *[]string `json:"UR_lv"`
	UrName                 *[]string `json:"UR_name"`
	UrType                 *[]string `json:"UR_type"`
	UrRank                 *[]string `json:"UR_rank"`
	UrKouka                *[]string `json:"UR_kouka"`
	UrPage                 *[]string `json:"UR_page"`
	IsDispArtizan          *string   `json:"is_disp_artizan"`
	JiLv                   *[]string `json:"JI_lv"`
	JiName                 *[]string `json:"JI_name"`
	JiTiming               *[]string `json:"JI_timing"`
	JiKouka                *[]string `json:"JI_kouka"`
	JiPage                 *[]string `json:"JI_page"`
	IsDispMaryoku          *string   `json:"is_disp_maryoku"`
	Mlv5                   *string   `json:"MLv5"`
	Mlv6                   *string   `json:"MLv6"`
	Mlv7                   *string   `json:"MLv7"`
	Mlv8                   *string   `json:"MLv8"`
	Mlv9                   *string   `json:"MLv9"`
	Mlv17                  *string   `json:"MLv17"`
	Mlv21                  *string   `json:"MLv21"`
	Nb5Dsp                 *string   `json:"NB5_dsp"`
	MmTokugi               *string   `json:"MM_Tokugi"`
	ArmsMaryokuSum         *string   `json:"arms_maryoku_sum"`
	Maryoku5               *string   `json:"maryoku5"`
	Maryoku6               *string   `json:"maryoku6"`
	Maryoku7               *string   `json:"maryoku7"`
	Maryoku8               *string   `json:"maryoku8"`
	Maryoku9               *string   `json:"maryoku9"`
	Maryoku17              *string   `json:"maryoku17"`
	Maryoku21              *string   `json:"maryoku21"`
	IsDispFailys           *string   `json:"is_disp_failys"`
	FailyTab1              *string   `json:"faily_tab1"`
	FailyTab2              *string   `json:"faily_tab2"`
	FailyTab3              *string   `json:"faily_tab3"`
	FailyTab4              *string   `json:"faily_tab4"`
	FailyTab5              *string   `json:"faily_tab5"`
	FailyTab6              *string   `json:"faily_tab6"`
	FailyTabText           *string   `json:"faily_tab_text"`
	IsDispSkill            *string   `json:"is_disp_skill"`
	SkillHeader            *[]string `json:"skill_header"`
	SkillName              *[]string `json:"skill_name"`
	SkillID                *[]string `json:"skill_id"`
	SkillTaisho            *[]string `json:"skill_taisho"`
	SkillRange             *[]string `json:"skill_range"`
	SkillShape             *[]string `json:"skill_shape"`
	SkillTime              *[]string `json:"skill_time"`
	SkillCost              *[]string `json:"skill_cost"`
	SkillLimit             *[]string `json:"skill_limit"`
	SkillMemo              *[]string `json:"skill_memo"`
	SkillShozoku           *[]string `json:"skill_shozoku"`
	IsDispHorse            *string   `json:"is_disp_horse"`
	HorseName              *string   `json:"horse_name"`
	HorseLv                *string   `json:"horse_lv"`
	HorseSpeed             *string   `json:"horse_speed"`
	HorseKnown             *string   `json:"horse_known"`
	HorseWeaken            *string   `json:"horse_weaken"`
	HorseWeakeneffect      *string   `json:"horse_weakeneffect"`
	HorseMemo              *string   `json:"horse_memo"`
	Horse1Name             *string   `json:"horse1_name"`
	Horse1Hr               *string   `json:"horse1_hr"`
	Horse1Mr               *string   `json:"horse1_mr"`
	Horse1Hit              *string   `json:"horse1_hit"`
	Horse1Dmg              *string   `json:"horse1_dmg"`
	Horse1Evd              *string   `json:"horse1_evd"`
	Horse1Def              *string   `json:"horse1_def"`
	Horse1Hp               *string   `json:"horse1_hp"`
	Horse1Mp               *string   `json:"horse1_mp"`
	HorsesMemo             *string   `json:"horses_memo"`
	Horse2Name             *string   `json:"horse2_name"`
	Horse2Hr               *string   `json:"horse2_hr"`
	Horse2Mr               *string   `json:"horse2_mr"`
	Horse2Hit              *string   `json:"horse2_hit"`
	Horse2Dmg              *string   `json:"horse2_dmg"`
	Horse2Evd              *string   `json:"horse2_evd"`
	Horse2Def              *string   `json:"horse2_def"`
	Horse2Hp               *string   `json:"horse2_hp"`
	Horse2Mp               *string   `json:"horse2_mp"`
	Horse3Name             *string   `json:"horse3_name"`
	Horse3Hr               *string   `json:"horse3_hr"`
	Horse3Mr               *string   `json:"horse3_mr"`
	Horse3Hit              *string   `json:"horse3_hit"`
	Horse3Dmg              *string   `json:"horse3_dmg"`
	Horse3Evd              *string   `json:"horse3_evd"`
	Horse3Def              *string   `json:"horse3_def"`
	Horse3Hp               *string   `json:"horse3_hp"`
	Horse3Mp               *string   `json:"horse3_mp"`
	EhorseHitExtend        *string   `json:"ehorse_hit_extend"`
	EhorsePowerExtend      *string   `json:"ehorse_power_extend"`
	EhorseEvationExtend    *string   `json:"ehorse_evation_extend"`
	EhorseHrExtend         *string   `json:"ehorse_hr_extend"`
	EhorseMrExtend         *string   `json:"ehorse_mr_extend"`
	IsDispLegion           *string   `json:"is_disp_legion"`
	KkLv                   *[]string `json:"KK_lv"`
	KkName                 *[]string `json:"KK_name"`
	KkTiming               *[]string `json:"KK_timing"`
	KkKouka                *[]string `json:"KK_kouka"`
	KkZentei               *[]string `json:"KK_zentei"`
	KkPage                 *[]string `json:"KK_page"`
	LegionName             *string   `json:"legion_name"`
	LegionPrice            *string   `json:"legion_price"`
	LegionPower            *string   `json:"legion_power"`
	LegionMax              *string   `json:"legion_max"`
	LegionMemo             *string   `json:"legion_memo"`
	IsDispHonor            *string   `json:"is_disp_honor"`
	HonorItemName          *[]string `json:"honor_item_name"`
	HonorItemPoint         *[]string `json:"honor_item_point"`
	HonorItemMemo          *[]string `json:"honor_item_memo"`
	HonorPointSum          *string   `json:"honor_point_sum"`
	HonoroutItemName       *[]string `json:"honorout_item_name"`
	HonoroutItemPoint      *[]string `json:"honorout_item_point"`
	Honoroutchkdeleting    *string   `json:"HonorOutchkDeleting"`
	HonoroutItemDeleting   *[]string `json:"honorout_item_deleting"`
	HonoroutItemMemo       *[]string `json:"honorout_item_memo"`
	UsedHonorPoint         *string   `json:"used_honor_point"`
	TotalHonorPoint        *string   `json:"total_honor_point"`
	NowHonorPoint          *string   `json:"now_honor_point"`
	IsDispSeichoHis        *string   `json:"is_disp_seicho_his"`
	IsUseSeichoHis         *string   `json:"is_use_seicho_his"`
	ExpHisSum              *string   `json:"exp_his_sum"`
	MoneyHisSum            *string   `json:"money_his_sum"`
	VSnHis                 *[]string `json:"V_SN_his"`
	SnNameHis              *[]string `json:"SN_name_his"`
	AdvExpHis              *[]string `json:"adv_exp_his"`
	PinZoroHis             *[]string `json:"1zoro_his"`
	BnsExpHis              *[]string `json:"bns_exp_his"`
	GetExpHis              *[]string `json:"get_exp_his"`
	GetMoneyHis            *[]string `json:"get_money_his"`
	SeichoMemoHis          *[]string `json:"seicho_memo_his"`
	IsDispPersonal         *string   `json:"is_disp_personal"`
	PcName                 *string   `json:"pc_name"`
	PcTags                 *string   `json:"pc_tags"`
	Age                    *string   `json:"age"`
	Sex                    *string   `json:"sex"`
	PcHeight               *string   `json:"pc_height"`
	PcWeight               *string   `json:"pc_weight"`
	ColorHair              *string   `json:"color_hair"`
	ColorEye               *string   `json:"color_eye"`
	ColorSkin              *string   `json:"color_skin"`
	VKegare                *string   `json:"V_kegare"`
	Keireki                *[]string `json:"keireki"`
	PcMakingMemo           *string   `json:"pc_making_memo"`
	PcMakingMemoRows       *string   `json:"pc_making_memo_rows"`
	Message                *string   `json:"message"`
	Game                   *string   `json:"game"`
	DataID                 *[]string `json:"data_id"`
	Phrase                 *string   `json:"phrase"`
	DataTitle              *string   `json:"data_title"`
	DodontofURL            *string   `json:"dodontof_url"`
	DodontofRoom           *string   `json:"dodontof_room"`
	KomaName               *string   `json:"koma_name"`
	DodontofImage          *string   `json:"dodontof_image"`
}
